from typing import TypedDict, Optional, Literal

class GapItem(TypedDict):
    found: str        # what was unclear / abbreviated / missing
    correction: str   # what it actually means, filled from domain knowledge

class ReflectionScores(TypedDict):
    accuracy: int
    completeness: int
    wikilink_density: int
    good_enough: bool
    gaps: list          # list[GapItem]
    feedback: str

class SearchResult(TypedDict):
    url: str
    title: str
    snippet: str

class NoteState(TypedDict):
    note_id: str
    image_paths: list[str]
    course_name: str
    module_name: str
    expansion_level: Literal["brief", "detailed", "deep dive"]
    user_notes: str          # student's own understanding / handwritten notes
    extracted_text: str
    diagram_descriptions: list[str]
    merge_decision: Literal["single", "separate"]
    uncertainties: list[str]
    search_queries: list[str]
    search_results: list[SearchResult]
    visuals: list[str]          # Mermaid diagram blocks generated by Claude
    draft_markdown: str
    image_embeds: list[str]
    reflection_scores: Optional[ReflectionScores]
    loop_count: int
    status: Literal["processing", "in_review", "approved", "rejected"]
    title: str
    thumbnail_path: str
    timestamp: str
    tags: list
